### ISSUE TITLE
Tutorial Server will not build.  

### ISSUE THREAD

**Issue by ghost** [swimos/tutorial#2] opened 2020-06-04 17:22 UTC
Followed the install instructions in the readme file, but when running I get the following error, and it is stuck at 80% executing.  Left running all night without change.  

Using Java 9.0.4

Extended terminal snippet:

1 | C:/Users/Prairie Rose/Downloads/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1079)
        at swim.io/swim.io.StationThread.select(Station.java:1005)
        at swim.io/swim.io.StationThread.run(Station.java:882)
error: unexpected ' '
 --> :1:17

to replicate:
1) Running on java 9.0.4 on windows
2) open admin command prompt
3) navigate to server folder
4) run "gradlew.bat run"
when execution gets to 80% error starts occurring.  

<==========---> 80% EXECUTING [9m 46s]
 --> :1:17
  |
1 | C:/Users/Prairie Rose/Downloads/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
error: unexpected ' '
 --> :1:17 swim.io/swim.io.StationThread.select(Station.java:1005)
  |
1 | C:/Users/Prairie Rose/Downloads/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)rver.java:62)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)ebService.java:118)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1079)HttpSocketService.java:51)
        at swim.io/swim.io.StationThread.select(Station.java:1005))
        at swim.io/swim.io.StationThread.run(Station.java:882)ava:453)
error: unexpected ' 'im.io.StationThread.doAccept(Station.java:1079)
 --> :1:17 swim.io/swim.io.StationThread.select(Station.java:1005)
  |     at swim.io/swim.io.StationThread.run(Station.java:882)
1 | C:/Users/Prairie Rose/Downloads/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)rver.java:62)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)ebService.java:118)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1079)HttpSocketService.java:51)
        at swim.io/swim.io.StationThread.select(Station.java:1005))
        at swim.io/swim.io.StationThread.run(Station.java:882)ava:453)
error: unexpected ' '
 --> :1:17
  |
1 | C:/Users/Prairie Rose/Downloads/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1079)
        at swim.io/swim.io.StationThread.select(Station.java:1005)
        at swim.io/swim.io.StationThread.run(Station.java:882)
error: unexpected ' '
 --> :1:17
  |DLE
1 | C:/Users/Prairie Rose/Downloads/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1079)
        at swim.io/swim.io.StationThread.select(Station.java:1005)
        at swim.io/swim.io.StationThread.run(Station.java:882)
<==========---> 80% EXECUTING [12m 59s]                                                                                 > IDLE
> :run
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE

**Comment by ajay-gov** [comment] 2020-06-04 18:56
@prrose thanks for reporting the issue.
We have tried with jdk11 on Windows and it is working for us. Could you please upgrade to jdk 11+ and try. jdk 9 and jdk10 are EOL, so it is better to use jdk11+ (we will update our Readme files soon)

Do make sure you have the latest version of the master for this project since we recently updated it.

**Comment by ajay-gov** [comment] 2020-06-05 20:20
Duplicate of issue #3

**Comment by ajay-gov** [comment] 2020-06-05 23:23
Closing since it's a duplicate

**Closed as completed by ajay-gov** 2020-06-05 23:23 UTC
