### ISSUE TITLE
Java 11 Parsing error of swim.codec

### ISSUE THREAD

**Issue by ghost** [swimos/tutorial#3] opened 2020-06-05 20:04 UTC
Hi.  Still trying to get the swim server to build on my machine.  I've tried Java 9,11, and 14, and Gradle versions 5.1, 6.0.1, 6.3, 6.5. on Windows 10.  

I downloaded a fresh version of the tutorial repo this afternoon, knowing that you recently updated it.  

Using java 11.0.7 and gradle 6.0.1 which matches the gradlew version:
 
I get the following error at 80% execution.  

Prairie Rose@DESKTOP-4SLV1D8 MINGW64 ~/Downloads/tutorial-master/tutorial-master/server
$ java -version
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

Prairie Rose@DESKTOP-4SLV1D8 MINGW64 ~/Downloads/tutorial-master/tutorial-master/server
$ gradle -v

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Oracle Corporation 11.0.7+8-LTS)
OS:           Windows 10 10.0 amd64

Prairie Rose@DESKTOP-4SLV1D8 MINGW64 ~/Downloads/tutorial-master/tutorial-master/server
$ ./gradlew.bat -v

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Oracle Corporation 11.0.7+8-LTS)
OS:           Windows 10 10.0 amd64

Prairie Rose@DESKTOP-4SLV1D8 MINGW64 ~/Downloads/tutorial-master/tutorial-master/server
$ ./gradlew run
Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details

> Task :run
Running Tutorial plane...
error: unexpected ' '
 --> :1:17
  |
1 | C:/Users/Prairie Rose/Downloads/tutorial-master/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1079)
        at swim.io/swim.io.StationThread.select(Station.java:1005)
        at swim.io/swim.io.StationThread.run(Station.java:882)
error: unexpected ' '
 --> :1:17
  |
1 | C:/Users/Prairie Rose/Downloads/tutorial-master/tutorial-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:142)
        at swim.uri/swim.uri.UriParser.parsePathString(UriParser.java:214)
        at swim.uri/swim.uri.UriPath.parse(UriPath.java:314)
        at swim.service.web/swim.service.web.WebServer.<init>(WebServer.java:62)
        at swim.service.web/swim.service.web.WebService.createServer(WebService.java:118)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:51)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:117)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1079)
        at swim.io/swim.io.StationThread.select(Station.java:1005)
        at swim.io/swim.io.StationThread.run(Station.java:882)
<==========---> 80% EXECUTING [19s]
> :run

**Comment by ajay-gov** [comment] 2020-06-05 20:19
@prrose sorry about the error you are encountering. We can't seem to reproduce it locally so can you help us troubleshoot by trying the following- Please remove line #7 (https://github.com/swimos/tutorial/blob/master/server/src/main/resources/server.recon#L7) from the `server.recon` file i.e the line: ` documentRoot: "./ui/"` and then rerun the gradle command `.\gradlew.bat run`

**Comment by SirCipher** [comment] 2020-06-05 21:24
Hi @prrose, sorry that you've been having issues with this. It seems like the parser doesn't like the space your username. If you move the tutorial folder to a path that doesn't contain any spaces then it should solve the issue that you've been having.

**Comment by ajay-gov** [comment] 2020-06-10 16:09
@prrose Did removing the space fix the issue? Sorry for this, we will file an issue with the core library regarding this.

**Comment by ghost** [comment] 2020-06-10 18:27
Yes it did!  Thank you.  I have a space in my name, so I had to move it outside of the user folder structure.

**Comment by ajay-gov** [comment] 2020-06-10 19:38
@prrose thank you for discovering this issue for us. We have filed an issue with the [swimos/swim repo]((https://github.com/swimos/swim/issues/56).

**Comment by ajay-gov** [comment] 2020-06-10 19:38
Closing, since this is an issue with the swim core libraries, please refer to [issue 56 in the swimos/swim repo](https://github.com/swimos/swim/issues/56)

**Closed as completed by ajay-gov** 2020-06-10 19:38 UTC
